name: Render deploy

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Setup
        run: make install
        env:
          DUMMY_USER: ${{ vars.DUMMY_USER }}
          DUMMY_PASSWORD: ${{ vars.DUMMY_PASSWORD }}

      - name: Run tests
        run: make test

      - name: Run linters
        run: make lint
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          curl ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
